# Generated by Django 5.2.5 on 2025-09-04 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('idCat', models.AutoField(primary_key=True, serialize=False)),
                ('nomCat', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rayon',
            fields=[
                ('idRayon', models.AutoField(primary_key=True, serialize=False)),
                ('nomRayon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('refProd', models.AutoField(primary_key=True, serialize=False)),
                ('intituleProd', models.CharField(max_length=200)),
                ('prixUnitaireProd', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='produits', to='monApp.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Contenir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qte', models.PositiveSmallIntegerField()),
                ('refProd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monApp.produit')),
                ('idrayon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='monApp.rayon')),
            ],
        ),
    ]
