# Generated by Django 5.2.5 on 2025-09-04 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contenir',
            old_name='idrayon',
            new_name='nomRayon',
        ),
        migrations.RenameField(
            model_name='contenir',
            old_name='refProd',
            new_name='nomprod',
        ),
        migrations.AlterUniqueTogether(
            name='contenir',
            unique_together={('nomprod', 'nomRayon')},
        ),
    ]
