# Generated by Django 5.2.5 on 2025-09-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0002_rename_idrayon_contenir_nomrayon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='dateDeFabrication',
            field=models.DateField(auto_now=True),
        ),
    ]
