# Generated by Django 5.2.5 on 2025-09-04 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0003_produit_datedefabrication'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statut',
            fields=[
                ('idStatut', models.AutoField(primary_key=True, serialize=False)),
                ('libelleStatus', models.CharField(max_length=200)),
            ],
        ),
    ]
