# Generated by Django 5.2.5 on 2025-09-08 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0005_produit_statut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statut',
            old_name='libelleStatus',
            new_name='libelléStatut',
        ),
    ]
