# Generated by Django 5.2.5 on 2025-09-08 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monApp', '0006_rename_libellestatus_statut_libelléstatut'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statut',
            old_name='libelléStatut',
            new_name='libelleStatut',
        ),
    ]
